name: OpenMath
version: 11.3.1
date: 08/01/2016
description: OpenMath functionality in GAP

authors:
    - name: Marco Costantini
    - name: Alexander Konovalov
      url: http://blogs.cs.st-andrews.ac.uk/alexk/
    - name: Max Nicosia
      url: mailto:ln73@st-andrews.ac.uk
    - name: Andrew Solomon
      url: http://www.illywhacker.net/

maintainers:
    - name: Alexander Konovalov
      url: http://blogs.cs.st-andrews.ac.uk/alexk/
    - name: Max Nicosia
      url: mailto:ln73@st-andrews.ac.uk

GAP: ">=4.7"

needed-pkgs:
    - name: "GapDoc"
      version: ">= 1.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 3.0"
      url: "https://gap-packages.github.io/io"

www: http://www.cs.st-andrews.ac.uk/~alexk/openmath/
readme: README.md
packageinfo: http://www.cs.st-andrews.ac.uk/~alexk/openmath/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www.cs.st-andrews.ac.uk/~alexk/openmath/openmath-11.3.1.tar.gz

abstract: This package provides an <a href="http://www.openmath.org/">OpenMath</a> phrasebook for <span class="pkgname">GAP</span>. This package allows <span class="pkgname">GAP</span> users to import and export mathematical objects encoded in OpenMath, for the purpose of exchanging them with other applications that are OpenMath enabled.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
